# Generated by Django 6.1 on 2026-08-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CONVERTED', 'Converted to FIR'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(max_length=50, unique=True)),
                ('formal_description', models.TextField(blank=True)),
                ('suggested_sections', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('INVESTIGATION', 'Under Investigation'), ('CLOSED', 'Closed')], default='REGISTERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
