# Generated by Django 6.1 on 2026-08-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
