# Generated by Django 6.1 on 2026-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='urgency',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10, null=True),
        ),
    ]
